Select Block from iframe and its config appear in sidebar
collective/volto-hydra pull request #51
Opened 2024-06-17 09:06 UTC by MAX-786

Fixes #23

2024-06-17 09:54 UTC, MAX-786 commented
> I am thinking to use volto's block engine to render these blocks behind the iframe and set the selected prop based on the block clicked in iframe.

AFAIK See This [BlocksForm](https://github.com/collective/volto-hydra/blob/687cacd18a7e0d1221209c373bc6b13876f3188c/packages/volto-hydra/src/customizations/components/manage/Form/Form.jsx#L703C13-L734C15)  renders the blocks in Volto and Block [Edit](https://github.com/collective/volto-hydra/blob/687cacd18a7e0d1221209c373bc6b13876f3188c/packages/volto-hydra/src/customizations/components/manage/Blocks/Block/Edit.jsx#L88) component handles displaying the selected block's settings in the sidebar.  So to update Sidebar, what if we use This Block Edit Component to set this.props.selected  to true whenever this.state.selectedBlock.uid matches with this.props.id.

2024-06-17 19:10 UTC, JeffersonBledsoe commented
> > I am thinking to use volto's block engine to render these blocks behind the iframe and set the selected prop based on the block clicked in iframe.
> 
> AFAIK See This [BlocksForm](https://github.com/collective/volto-hydra/blob/687cacd18a7e0d1221209c373bc6b13876f3188c/packages/volto-hydra/src/customizations/components/manage/Form/Form.jsx#L703C13-L734C15) renders the blocks in Volto and Block [Edit](https://github.com/collective/volto-hydra/blob/687cacd18a7e0d1221209c373bc6b13876f3188c/packages/volto-hydra/src/customizations/components/manage/Blocks/Block/Edit.jsx#L88) component handles displaying the selected block's settings in the sidebar. So to update Sidebar, what if we use This Block Edit Component to set this.props.selected to true whenever this.state.selectedBlock.uid matches with this.props.id.

As discussed in this weeks sprint planning, this works fine as all of the sidebar updating logic is kept in this component. As long as the actual rendering of the block is disabled (and any other potential side-effects the component may have), it should be fine to re-use this component for now.
An argument could be made that this logic should be split up and moved to another file in core Volto.

2024-06-18 15:12 UTC, djay requested changes

2024-06-18 15:12 UTC, djay commented on README.md
> +Add the `data-block-uid={}` attribute to your rendered block html and call the `enableBlockClickListener()` provided by 'hydra.js' whenever your component is mounted.
doesn't it need to include the block id? 
Also they need to know its goes on the outer most container of the block

2024-06-18 15:12 UTC, djay commented on README.md
> +Add the `data-block-uid={}` attribute to your rendered block html and call the `enableBlockClickListener()` provided by 'hydra.js' whenever your component is mounted.
An example might help also

2024-06-19 12:59 UTC, JeffersonBledsoe requested changes
Still needs the automatic subscription when blocks are changed or the page is changed. I'll review more closely once that is in place

2024-06-19 12:59 UTC, JeffersonBledsoe commented on hydra.js
> +  }
@MAX-786 This still needs the automatic subscription to page changes or block changes, such as by using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

2024-06-20 08:10 UTC, MAX-786 commented on hydra.js
> +  }
hmm actually what this does is set click event listener for WHOLE document and then it looks for closest ancestor or itself with that attr. So, even if the dom is updated by adminUI (block add/delete)  it will still can be selected .
Once the block add button is done we can try that out and take it there?

2024-06-20 08:31 UTC, djay reviewed
are you removing enableBlockClickListener() later or now?

2024-06-20 08:31 UTC, djay commented on README.md
> +Add the `data-block-uid={}` attribute to your rendered block html and call the `enableBlockClickListener()` provided by 'hydra.js' whenever your component is mounted.
```suggestion
Add the `data-block-uid={<<BLOCK_UID>>}` attribute to your outer most container of the rendered block html and call the `enableBlockClickListener()` provided by 'hydra.js' whenever your component is mounted.
```

2024-06-20 08:32 UTC, JeffersonBledsoe commented on hydra.js
> +  }
Hmmm, this might be enough to prove the concept for the PoC then! In a production environment it wouldn't be enough as the blocks wouldn't be accessible nor can you interact with them via the keyboard. you would need to make anything that is clickable either the a button, or have the relevant role (i.e. button), give it all of the focus and keyboard events and give it a label so that it is descriptive to accessibility tools such as a screen reader.

2024-06-20 08:56 UTC, MAX-786 commented on hydra.js
> +  }
>  nor can you interact with them via the keyboard. you would need to make anything that is clickable either the a button, or have the relevant role (i.e. button), give it all of the focus and keyboard events and give it a label so that it is descriptive to accessibility tools such as a screen reader.

so is it oki to let it merge and upgrade it later ?

2024-06-20 09:03 UTC, MAX-786 commented
> are you removing enableBlockClickListener() later or now?

done

2024-06-20 09:43 UTC, MAX-786 commented on packages/volto-hydra/src/customizations/components/manage/Blocks/Block/Edit.jsx
> +      selected: state.selectedBlock.uid === props.id,
mapped `this.props.selected` with checking the state.selectedBlock.uid matches props.id, since selectedBlock.uid is set by Iframe component

2024-06-20 09:45 UTC, MAX-786 commented
> @MAX-786 It's a little difficult to see what's changed in the Edit shadow, but I think it's all good apart from the few comments I left

nothing major. let me point them out

2024-06-20 12:58 UTC, JeffersonBledsoe commented
@MAX-786 All fine on the changes in the Edit shadow then. I've merged #49 into main and brought the changes into this PR. Can you check this PR over again with your frontend and fix up the comments I'd left please all good? We're good to use the GitHub Squash & Merge then as I resolved the conflicts with the other branches

2024-06-20 13:00 UTC, MAX-786 commented
> fix up the comments I'd left please all good? We're good to use the GitHub Squash & Merge then as I resolved the conflicts with the other branches

Yep I'll fix them up right now

2024-06-20 13:28 UTC, JeffersonBledsoe commented
@MAX-786 Yes, I've merged the changes from #49 into this one (and also into #60 )

2024-06-21 13:05 UTC, MAX-786 commented
@djay @JeffersonBledsoe LGTM!

2024-06-22 00:40 UTC, djay approved these changes

2024-06-22 13:41 UTC, merged